wandb_version: 1

batch_size:
  value: 128
cell_type:
  value: gru
clip:
  value: 1
data_dir:
  value: .
dropout:
  value: 0
embedding_size:
  value: 128
hidden_size:
  value: 64
language:
  value: ta
learning_rate:
  value: 0.007985198325782037
max_seq_len:
  value: 50
momentum:
  value: 0.9
n_epochs:
  value: 20
num_layers:
  value: 3
optimizer:
  value: adam
rmsprop_alpha:
  value: 0.99
scheduler:
  value: plateau
scheduler_factor:
  value: 0.5
scheduler_patience:
  value: 5
scheduler_t_max:
  value: 20
teacher_forcing_ratio:
  value: 0.7
use_attention:
  value: false
weight_decay:
  value: 0
