wandb_version: 1

batch_size:
  value: 64
cell_type:
  value: rnn
clip:
  value: 1
data_dir:
  value: .
decoder_layers:
  value: 3
dropout:
  value: 0.3
embedding_size:
  value: 32
encoder_layers:
  value: 3
hidden_size:
  value: 64
language:
  value: ta
learning_rate:
  value: 0.0001258266030694314
max_seq_len:
  value: 50
momentum:
  value: 0
n_epochs:
  value: 10
optimizer:
  value: sgd
rmsprop_alpha:
  value: 0.99
scheduler:
  value: cosine
scheduler_factor:
  value: 0.5
scheduler_patience:
  value: 5
scheduler_t_max:
  value: 20
teacher_forcing_ratio:
  value: 0.5
use_attention:
  value: true
weight_decay:
  value: 0.001
