_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.11
            "8":
                - 3
                - 8
            "12": 0.19.11
            "13": windows-amd64
batch_size:
    value: 128
cell_type:
    value: lstm
clip:
    value: 1
data_dir:
    value: .
decoder_layers:
    value: 2
dropout:
    value: 0.2
embedding_size:
    value: 64
encoder_layers:
    value: 1
hidden_size:
    value: 64
language:
    value: ta
learning_rate:
    value: 0.0001539303371304956
max_seq_len:
    value: 50
momentum:
    value: 0
n_epochs:
    value: 10
optimizer:
    value: rmsprop
rmsprop_alpha:
    value: 0.99
scheduler:
    value: none
scheduler_factor:
    value: 0.5
scheduler_patience:
    value: 5
scheduler_t_max:
    value: 20
teacher_forcing_ratio:
    value: 0.7
use_attention:
    value: false
weight_decay:
    value: 0.001
